### ISSUE TITLE
some problems about the videos dataset download  

### ISSUE THREAD

**Issue by levelzly** [hazeld/rank-aware-attention-network#1]
1. python utils/download_videos.py data/BEST/BEST.csv <download_dir>  can't  download the dataset , then the outputdata directory just have the folder  about label.
2.and then run the code occur “[Errno 2] No such file or directory: 'youtube-dl': 'youtube-dl'”.
3.in the code,there no link about download dataset.
so,please give me some favor to deal with this problem.thank you.
looking forward to your reply.

**Comment by ZhouCX117** [comment]
Hello, how did you fix this problem?
